### ISSUE TITLE
Add option to `decompile-headless.sh` to list all functions in binary

### ISSUE THREAD

**Issue by xlauko** [lifting-bits/patchestry#43]
```[tasklist]
### Tasks
- [ ] Add option `-l,--list-functions` to show all know functions in processed binary
- [ ] This will require another ghidra script `ListFunctions.java`.
- [ ] For clarity rename `PatchestryScript.java` to `DecompileFunction.java` and update docs where needed.
- [ ] If ghidra ends with `PatchestryScript.java> Function not found:` let user know what are the options.
- [ ] Add option to decompile all functions in a file.
```
